### ISSUE TITLE
It crashes when I use put it in server mods folder

### ISSUE THREAD

**Issue by linqihao2333** [RakambdaOrg/FallingTree#244]
### Describe the bug

It crashes when I use put it in the server mods folder...

System: Ubuntu 20.04
Java version: openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-120.04, mixed mode, sharing)

### Minecraft version

1.18-rc3

### Fabric API version

0.43.1

### Mod version

2.14.3

### Relevant log output

```shell
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[18:59:56] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.18-rc3
[18:59:56] [main/INFO]: Loading for game Minecraft 1.18-rc3
[18:59:56] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[18:59:56] [main/INFO]: Loading 40 mods:
        - cloth-basic-math 0.6.0
        - cloth-config 6.0.42
        - fabric 0.43.1+1.18
        - fabric-api-base 0.4.1+b4f4f6cd14
        - fabric-api-lookup-api-v1 1.3.5+3ac43d9514
        - fabric-biome-api-v1 6.0.1+3ac43d9514
        - fabric-command-api-v1 1.1.6+3ac43d9514
        - fabric-commands-v0 0.2.5+b4f4f6cd14
        - fabric-containers-v0 0.1.18+d154e2c614
        - fabric-content-registries-v0 0.4.5+6f53a73d14
        - fabric-crash-report-info-v1 0.1.8+3ac43d9514
        - fabric-dimensions-v1 2.1.7+43d2957114
        - fabric-entity-events-v1 1.4.5+6b21378a14
        - fabric-events-interaction-v0 0.4.15+3ac43d9514
        - fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14
        - fabric-game-rule-api-v1 1.0.10+3ac43d9514
        - fabric-item-api-v1 1.2.7+3ac43d9514
        - fabric-item-groups-v0 0.3.3+3ac43d9514
        - fabric-lifecycle-events-v1 1.4.10+c15ca33514
        - fabric-loot-tables-v1 1.0.8+3ac43d9514
        - fabric-mining-level-api-v1 1.0.3+3ac43d9514
        - fabric-mining-levels-v0 0.1.7+b4f4f6cd14
        - fabric-networking-api-v1 1.0.18+3ac43d9514
        - fabric-networking-v0 0.3.5+b4f4f6cd14
        - fabric-object-builder-api-v1 1.10.13+3ac43d9514
        - fabric-object-builders-v0 0.7.7+3ac43d9514
        - fabric-particles-v1 0.2.9+526dc1ac14
        - fabric-registry-sync-v0 0.8.5+3ac43d9514
        - fabric-rendering-data-attachment-v1 0.3.3+d154e2c614
        - fabric-rendering-fluids-v1 0.1.18+3ac43d9514
        - fabric-resource-loader-v0 0.4.11+3ac43d9514
        - fabric-screen-handler-api-v1 1.1.11+3ac43d9514
        - fabric-structure-api-v1 2.0.8+295197a714
        - fabric-tag-extensions-v0 1.2.5+3ac43d9514
        - fabric-tool-attribute-api-v1 1.3.4+7de09f5514
        - fabric-transfer-api-v1 1.5.4+b4f4f6cd14
        - fabricloader 0.12.5
        - fallingtree 2.14.3
        - java 17
        - minecraft 1.18-rc.3
[18:59:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/linqihao2333/mc/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[18:59:57] [main/INFO]: Compatibility level set to JAVA_16
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
        ... 2 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fallingtree.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:87)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
        ... 13 more
```

**Comment by Rakambda** [comment]
Maybe fabric hasn't fully transitioned to Java 17 for the mixins.

What if you try with this version?
 https://www.dropbox.com/t/DdjHwwz3i3mv8T3W

**Comment by linqihao2333** [comment]
ohh! It works!
