### ISSUE TITLE
Mod fallingtree provides a broken implementation of ModMenuApi

### ISSUE THREAD

**Issue by jonas-w** [RakambdaOrg/FallingTree#293]
### Describe the bug

When starting minecraft with the mod loaded this error pops up and the mod doesn't work!

### Minecraft version

1.18.1

### Fabric API version

0.46.0

### Mod version

3.1.0

### Relevant log output

```shell
java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/gui/registry/GuiRegistry
	at fr.raksrinana.fallingtree.fabric.ModMenuImpl.<clinit>(ModMenuImpl.java:17)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:67)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.gui.registry.GuiRegistry
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more
```

**Comment by Rakambda** [comment]
Do you have ClothConfig mod ? If yes what version ?

**Comment by Rakambda** [comment]
Does [this build](https://github.com/RakSrinaNa/FallingTree/actions/runs/1702534400) (artifact section at the bottom, you can download a zip containing the mod file) fixes the issue ?

**Comment by jonas-w** [comment]
With this build it won't show that error but it's still not working. 

Do i need to change something in the config before using it?

**Comment by Rakambda** [comment]
"not working", will have to explain it further.

Did you enchant your axe?

**Comment by jonas-w** [comment]
Okay sorry that "not working" part was my issue. 
It also works with the normal version after enchanting my axe.
But after receiving that error i thought it wouldn't work because of that error.

Is this somewhere written that it needs to be enchanted?

**Comment by Rakambda** [comment]
https://github.com/RakSrinaNa/FallingTree/releases/tag/3.0.0

3.2.0 will disable the enchant by default for new comers. But for now it is activated by default.

**Comment by jonas-w** [comment]
Okay thank you.
