### ISSUE TITLE
Mod failed to load correctly with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [RakambdaOrg/FallingTree#377]
### Describe the bug

I tried to load this mod with the latest version of forge and got the following error message:
![image](https://user-images.githubusercontent.com/18667108/178123363-5a431bbf-771e-4d0a-b13b-2f7cb46d0604.png)

### Minecraft version

1.19

### Forge version

41.0.85

### Mod version

3.7.0

### Relevant log output

```
---- Minecraft Crash Report ----
// My bad.

Time: 7/9/22, 5:30 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.85-universal.jar%23202!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.0.85-universal.jar%23202!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23197!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.85.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD fallingtree --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.85.jar%23199!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.85.jar%23198!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ClientPlayerNetworkEvent$LoggedOutEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at fr.raksrinana.fallingtree.forge.common.FallingTreeCommonsImpl.registerForge(FallingTreeCommonsImpl.java:219) ~[FallingTree-1.19-3.7.0.jar%23165!/:3.7.0] {re:classloading}
		at fr.raksrinana.fallingtree.forge.FallingTree.<init>(FallingTree.java:35) ~[FallingTree-1.19-3.7.0.jar%23165!/:3.7.0] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.85.jar%23199!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.85.jar%23198!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: FallingTree-1.19-3.7.0.jar
	Failure message: FallingTree (fallingtree) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 3.7.0
	Mod Issue URL: https://github.com/RakSrinaNa/FallingTree/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at fr.raksrinana.fallingtree.forge.common.FallingTreeCommonsImpl.registerForge(FallingTreeCommonsImpl.java:219) ~[FallingTree-1.19-3.7.0.jar%23165!/:3.7.0] {re:classloading}
	at fr.raksrinana.fallingtree.forge.FallingTree.<init>(FallingTree.java:35) ~[FallingTree-1.19-3.7.0.jar%23165!/:3.7.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.85.jar%23199!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.85.jar%23198!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2351930888 bytes (2242 MiB) / 3791650816 bytes (3616 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8190
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29019.80
	Virtual memory used (MB): 20724.29
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 1306.33
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.85.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.85.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.85.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.85.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.85.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		AwesomeFlooring-Forge-1.19-2.0.1.jar              |Awesome Flooring              |awesomeflooring               |1                   |COMMON_SET|Manifest: NOSIGNATURE
		MoreStairs-1.19-2.7.0.jar                         |More Stairs                   |morestairs                    |2.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		moredoors-1.19-1.27.jar                           |MoreDoors                     |moredoors                     |1.0.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		cutandcolored-9.3-1.19.jar                        |Cut And Colored               |cutandcolored                 |9.3                 |COMMON_SET|Manifest: NOSIGNATURE
		ellemes-container-library-2.0.3+1.19-forge.jar    |Ellemes' Container Library    |ellemes_container_lib         |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		additionallanterns-1.0.1-forge-mc1.19.jar         |Additional Lanterns           |additionallanterns            |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		exlinecopperequipment-forge-1.19-v2.0.4.jar       |Copper Equipment              |exlinecopperequipment         |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.19-2.0.0.jar                |Library ferret                |libraryferret                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.19.jar                      |Macaw's Windows               |mcwwindows                    |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		BowInfinityFix-1.19.x-forge-2.5.0.jar             |Bow Infinity Fix              |bowinfinityfix                |2.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		material_elements_armor_tools_weapons_1.19-4.2.0.j|Material Elements Armor, Tools|material_elements_armor_tools_|4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paintings-1.0.3-mc1.19.jar                    |Macaw's Paintings             |mcwpaintings                  |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.25.2_Forge_1.19.jar              |Xaero's World Map             |xaeroworldmap                 |1.25.2              |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5rc3-forge.jar                |Journeymap                    |journeymap                    |5.8.5rc3            |COMMON_SET|Manifest: NOSIGNATURE
		exlineawnings-forge-1.19-v1.1.2.jar               |Exline's Awnings              |exlineawnings                 |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.19-1.9.7-forge.jar               |Nature's Compass              |naturescompass                |1.19-1.9.7-forge    |COMMON_SET|Manifest: NOSIGNATURE
		emeraldequipment-forge-1.19-v1.0.3.jar            |Emerald Equipment             |emeraldequipment              |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		additionalbars-3.3.1-beta+1.19.jar                |Additional Bars               |additionalbars                |3.3.1-beta          |COMMON_SET|Manifest: NOSIGNATURE
		premium_wood-1.19-1.4.0.jar                       |Premium Wood                  |premium_wood                  |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		toolleveling-1.19-1.3.1.jar                       |Tool Leveling                 |toolleveling                  |1.19 - 1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.19.jar                        |Macaw's Doors                 |mcwdoors                      |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		ExplorersCompass-1.19-1.2.3-forge.jar             |Explorer's Compass            |explorerscompass              |1.19-1.2.3-forge    |COMMON_SET|Manifest: NOSIGNATURE
		material_elements_decorative_1.19-4.2.0.jar       |Material Elements Decorative  |material_elements_decorative  |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-7.0.72-forge.jar                     |Cloth Config v4 API           |cloth_config                  |7.0.72              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.0.85-universal.jar                  |Forge                         |forge                         |41.0.85             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mcw-paths-1.0.0-mc1.19.jar                        |Macaw's Paths and Pavings     |mcwpaths                      |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		invisibilitycloak-forge-1.19-2.1.0.jar            |Invisibility Cloak            |invisibilitycloak             |1.19-2.1.0          |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.3-mc1.19.jar                      |Macaw's Bridges               |mcwbridges                    |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		block_variants-1.19-4.1.jar                       |Block Variants                |block_variants                |4.1                 |COMMON_SET|Manifest: NOSIGNATURE
		woodarmor-forge-1.19-v1.0.3.jar                   |Wooden Armors (+ Stone Armor) |woodarmor                     |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.119.jar             |TerraBlender                  |terrablender                  |2.0.0.119           |COMMON_SET|Manifest: NOSIGNATURE
		amethystequipment-forge-1.19-v1.0.4.jar           |Amethyst Equipment            |amethystequipment             |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		material_elements_1.19-4.2.0.jar                  |Material Elements             |material_elements             |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		another_furniture-forge-2.0.0-1.19.jar            |Another Furniture             |another_furniture             |2.0.0-1.19          |COMMON_SET|Manifest: NOSIGNATURE
		warhammersmod-forge-1.19-v1.0.3.jar               |War-Hammers Mod               |warhammersmod                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.6-mc1.19.jar                    |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.0.5-mc1.19.jar                       |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		glow_sticks_1.19-2.2.0.jar                        |Glow Sticks                   |glow_sticks                   |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.19.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |COMMON_SET|Manifest: NOSIGNATURE
		barkcarpets-forge-1.19-v1.0.3.jar                 |Bark Carpets                  |barkcarpets                   |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		woodarmorhorse-forge-1.19-v1.0.3.jar              |Wooden Horse Armors           |woodarmorhorse                |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.2_Forge_1.19.jar             |Xaero's Minimap               |xaerominimap                  |22.11.2             |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.0-4.28.jar                        |Collective                    |collective                    |4.28                |COMMON_SET|Manifest: NOSIGNATURE
		boneequipment-forge-1.19-v1.0.3.jar               |Bone Equipment                |boneequipment                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		exlinedoors-forge-1.19-v2.3.5.jar                 |Exline's Doors                |exlinedoors                   |2.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		obsidianequipment-forge-1.19-v1.0.3.jar           |Obsidian Equipment            |obsidianequipment             |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		KrystalCraft-0.0.2.9.jar                          |KrystalCraft                  |krystalcraft                  |0.0.2.9             |COMMON_SET|Manifest: NOSIGNATURE
		expandedstorage-8.0.0+1.19-forge.jar              |Expanded Storage              |expandedstorage               |8.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-roofs-2.1.2-mc1.19.jar                        |Macaw's Roofs                 |mcwroofs                      |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.8.29-forge.jar                     |Architectury                  |architectury                  |5.8.29              |COMMON_SET|Manifest: NOSIGNATURE
		mcw-furniture-3.0.0-mc1.19.jar                    |Macaw's Furniture             |mcwfurnitures                 |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		BetterF3-1.3.1-Forge-1.19.jar                     |BetterF3                      |betterf3                      |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.19-3.7.0.jar                        |FallingTree                   |fallingtree                   |3.7.0               |ERROR     |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		AllArrowsInfinityFix-FORGE-1.3-mc1.19.jar         |All Arrows Infinity Fix       |allarrowsinfinityfix          |1.3                 |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.19.jar                       |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: bef3f6b5-128a-44e6-9726-6367cd5609f6
	FML: 41.0
	Forge: net.minecraftforge:41.0.85
```

**Comment by Rakambda** [comment]
Forge [41.0.64](https://github.com/MinecraftForge/MinecraftForge/commit/4d074f0a1ef1d774786b4f1e1e3e827a9bf576e0#diff-7c6afac67693f696f4e5974a4ded36f796e2291e227a929a776e2a5b610d7ca6R94) introduced a breaking change.

https://github.com/MinecraftForge/MinecraftForge/pull/8786

Will fix that and make a release.

**Comment by Gamemassa** [comment]
Can confirm, FallingTree 3.7.1 is definitely working with Forge 41.0.64+. Thanks again for the rapid response and support!
