### ISSUE TITLE
BlockEvent$BreakEvent error and crash

### ISSUE THREAD

**Issue by Gamemassa** [RakambdaOrg/FallingTree#379]
### Describe the bug

![image](https://user-images.githubusercontent.com/18667108/178519406-833e9e6e-a079-4ae4-9a7e-2e01a2a475af.png)

[crash-2022-07-12_10.49.11-fml.txt](https://github.com/RakSrinaNa/FallingTree/files/9094180/crash-2022-07-12_10.49.11-fml.txt)

### Minecraft version

1.19

### Forge version

41.0.94

### Mod version

3.7.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/12/22, 10:49 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.94-universal.jar%23204!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.0.94-universal.jar%23204!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.94.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD fallingtree --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/BlockEvent$BreakEvent
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
		at fr.raksrinana.fallingtree.forge.FallingTree.<clinit>(FallingTree.java:18) ~[FallingTree-1.19-3.7.1.jar%23165!/:3.7.1] {re:classloading,pl:epic_rei_lmao:B}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.94.jar%23201!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.94.jar%23200!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: FallingTree-1.19-3.7.1.jar
	Failure message: FallingTree (fallingtree) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/world/BlockEvent$BreakEvent
	Mod Version: 3.7.1
	Mod Issue URL: https://github.com/RakSrinaNa/FallingTree/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.world.BlockEvent$BreakEvent
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at fr.raksrinana.fallingtree.forge.FallingTree.<clinit>(FallingTree.java:18) ~[FallingTree-1.19-3.7.1.jar%23165!/:3.7.1] {re:classloading,pl:epic_rei_lmao:B}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.94.jar%23201!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.94.jar%23200!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 584742208 bytes (557 MiB) / 905969664 bytes (864 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8190
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29019.80
	Virtual memory used (MB): 17771.20
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 1422.93
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.94.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.94.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.94.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.94.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.94.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		MoreStairs-1.19-2.7.0.jar                         |More Stairs                   |morestairs                    |2.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |COMMON_SET|Manifest: NOSIGNATURE
		rechiseled-1.0.10c-forge-mc1.19.jar               |Rechiseled                    |rechiseled                    |1.0.10c             |COMMON_SET|Manifest: NOSIGNATURE
		moredoors-1.19-1.27.jar                           |MoreDoors                     |moredoors                     |1.0.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		ellemes-container-library-2.0.4+1.19-forge.jar    |Ellemes' Container Library    |ellemes_container_lib         |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		additionallanterns-1.0.1a-forge-mc1.19.jar        |Additional Lanterns           |additionallanterns            |1.0.1a              |COMMON_SET|Manifest: NOSIGNATURE
		exlinecopperequipment-forge-1.19-v2.0.4.jar       |Copper Equipment              |exlinecopperequipment         |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.19.jar                      |Macaw's Windows               |mcwwindows                    |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		BowInfinityFix-1.19.x-forge-2.5.0.jar             |Bow Infinity Fix              |bowinfinityfix                |2.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		moreconcrete-1.4.2-1.19.jar                       |More Concrete                 |moreconcrete                  |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paintings-1.0.3-mc1.19.jar                    |Macaw's Paintings             |mcwpaintings                  |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.25.3_Forge_1.19.jar              |Xaero's World Map             |xaeroworldmap                 |1.25.3              |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.19-10.0+3.jar                 |Controlling                   |controlling                   |10.0+3              |COMMON_SET|Manifest: NOSIGNATURE
		exlineawnings-forge-1.19-v1.1.2.jar               |Exline's Awnings              |exlineawnings                 |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		RoughlyEnoughItems-plugin-compatibilities-forge-9.|REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.1.509             |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.19-1.9.7-forge.jar               |Nature's Compass              |naturescompass                |1.19-1.9.7-forge    |COMMON_SET|Manifest: NOSIGNATURE
		emeraldequipment-forge-1.19-v1.0.3.jar            |Emerald Equipment             |emeraldequipment              |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		additionalbars-3.3.1-beta+1.19.jar                |Additional Bars               |additionalbars                |3.3.1-beta          |COMMON_SET|Manifest: NOSIGNATURE
		configured-1.5.4-1.19.jar                         |Configured                    |configured                    |1.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.19.jar                        |Macaw's Doors                 |mcwdoors                      |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		ExplorersCompass-1.19-1.2.3-forge.jar             |Explorer's Compass            |explorerscompass              |1.19-1.2.3-forge    |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-7.0.73-forge.jar                     |Cloth Config v4 API           |cloth_config                  |7.0.73              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.0.94-universal.jar                  |Forge                         |forge                         |41.0.94             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mcw-paths-1.0.0-mc1.19.jar                        |Macaw's Paths and Pavings     |mcwpaths                      |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.3-mc1.19.jar                      |Macaw's Bridges               |mcwbridges                    |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		woodarmor-forge-1.19-v1.0.3.jar                   |Wooden Armors (+ Stone Armor) |woodarmor                     |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |COMMON_SET|Manifest: NOSIGNATURE
		amethystequipment-forge-1.19-v1.0.4.jar           |Amethyst Equipment            |amethystequipment             |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |COMMON_SET|Manifest: NOSIGNATURE
		macawsbridgesbop-1.19-1.0.jar                     |Macaw's Bridges - BOP         |macawsbridgesbop              |1.19-1.0            |COMMON_SET|Manifest: NOSIGNATURE
		baleofsugarcane-forge-41.0.85-mc-1.19-v1.0.1.jar  |Bale of Sugar Cane            |baleofsugarcane               |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		warhammersmod-forge-1.19-v1.0.3.jar               |War-Hammers Mod               |warhammersmod                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.6-mc1.19.jar                    |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.0.5-mc1.19.jar                       |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.19.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |COMMON_SET|Manifest: NOSIGNATURE
		barkcarpets-forge-1.19-v1.0.3.jar                 |Bark Carpets                  |barkcarpets                   |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		RoughlyEnoughItems-9.1.509.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.509             |COMMON_SET|Manifest: NOSIGNATURE
		mcwfencesbop-1.19-1.1.jar                         |Macaw's Fences - BOP          |mcwfencesbop                  |1.19-1.1            |COMMON_SET|Manifest: NOSIGNATURE
		woodarmorhorse-forge-1.19-v1.0.3.jar              |Wooden Horse Armors           |woodarmorhorse                |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19-74.jar                             |Patchouli                     |patchouli                     |1.19-74             |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.4_Forge_1.19.jar             |Xaero's Minimap               |xaerominimap                  |22.11.4             |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |COMMON_SET|Manifest: NOSIGNATURE
		boneequipment-forge-1.19-v1.0.3.jar               |Bone Equipment                |boneequipment                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		exlinedoors-forge-1.19-v2.3.5.jar                 |Exline's Doors                |exlinedoors                   |2.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		obsidianequipment-forge-1.19-v1.0.3.jar           |Obsidian Equipment            |obsidianequipment             |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-roofs-2.1.2-mc1.19.jar                        |Macaw's Roofs                 |mcwroofs                      |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		macawsroofsbop-1.19-1.0.jar                       |Macaw's Roofs - BOP           |macawsroofsbop                |1.19-1.0            |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.9.30-forge.jar                     |Architectury                  |architectury                  |5.9.30              |COMMON_SET|Manifest: NOSIGNATURE
		connectedglass-1.1.4b-forge-mc1.19.jar            |Connected Glass               |connectedglass                |1.1.4b              |COMMON_SET|Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.6.jar    |Oh The Biomes You'll Go       |byg                           |2.0.0.6             |COMMON_SET|Manifest: NOSIGNATURE
		macawsbridgesbyg-1.19-1.0.jar                     |Macaw's Bridges - BYG         |macawsbridgesbyg              |1.19-1.0            |COMMON_SET|Manifest: NOSIGNATURE
		mcwfencesbyg-1.19-1.0.jar                         |Macaw's Fences - BYG          |mcwfencesbyg                  |1.19-1.0            |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.19-3.7.1.jar                        |FallingTree                   |fallingtree                   |3.7.1               |ERROR     |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		AllArrowsInfinityFix-FORGE-1.3-mc1.19.jar         |All Arrows Infinity Fix       |allarrowsinfinityfix          |1.3                 |COMMON_SET|Manifest: NOSIGNATURE
		additionalbarsbop-3.3.1-beta+1.19.jar             |Additional Bars (Biomes o' Ple|additionalbarsbop             |3.3.1-beta          |COMMON_SET|Manifest: NOSIGNATURE
		GameMenuModOption-1.19-1.17.jar                   |Game Menu Mod Option          |gamemenumodoption             |1.17                |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.19.jar                       |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: b8266cb8-5b88-4b12-b789-4acd3b746554
	FML: 41.0
	Forge: net.minecraftforge:41.0.94
```

**Comment by Rakambda** [comment]
Probably linked to https://github.com/MinecraftForge/MinecraftForge/pull/8840, will look into it
