### ISSUE TITLE
[1.19.2] Exiting and trying to re-enter world without closing MC will get stuck on loading terrain screen

### ISSUE THREAD

**Issue by TelepathicGrunt** [RakambdaOrg/FallingTree#444]
### Describe the bug

Using Better Minecraft v9, I found if I was in a world, exiting the world without closing mc, and attempt to re-enter, the game is stuck on the Loading Terrain screen. Nothing happens afterwards. After doing a thread dump with VisualVM, it appears that the game has deadlocked on fallingtree on the server thread. No other threads had any worldgen code running. Very strange. 

Closing mc entirely and attempting to enter the world that way will work.

![image](https://user-images.githubusercontent.com/40846040/202905213-73fe9e48-7625-408b-a3d5-e67c7fface43.png)

### Minecraft version

1.19.2

### Fabric API version

0.64.0

### Mod version

1.12.2

### Relevant log output

```shell
"Server thread" #205 prio=5 os_prio=0 cpu=3734.38ms elapsed=160.66s tid=0x000001f80fb326d0 nid=0x2084 waiting on condition  [0x000000ad568fe000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
        - parking to wait for  <0x00000006e6400018> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.3/ForkJoinPool.java:3463)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.3/ForkJoinPool.java:3434)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.3/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.join(java.base@17.0.3/CompletableFuture.java:2117)
        at net.minecraft.class_3215.getChunkOffThread(class_3215.java:1189)
        at net.minecraft.class_3215.method_12121(class_3215.java:1154)
        at net.minecraft.class_1937.method_8402(class_1937.java:197)
        at net.minecraft.class_1937.method_22350(class_1937.java:6068)
        at fr.raksrinana.fallingtree.fabric.common.wrapper.LevelWrapper.getChunk(LevelWrapper.java:33)
        at fr.raksrinana.fallingtree.common.leaf.LeafBreakingHandler.onServerTick(LeafBreakingHandler.java:31)
        at fr.raksrinana.fallingtree.fabric.event.LeafBreakingListener.onEndTick(LeafBreakingListener.java:16)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$5195/0x0000000800e72518.onEndTick(Unknown Source)
        at net.minecraft.server.MinecraftServer.handler$dbl002$onEndTick(MinecraftServer.java:6321)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
        at net.minecraft.class_1132.method_3748(class_1132.java:98)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at net.minecraft.server.MinecraftServer$$Lambda$18184/0x00000008022586a0.run(Unknown Source)
        at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)
```

**Comment by Rakambda** [comment]
You mention Better MC, it's a mod pack right?

If so, can you reproduce this with just Falling Tree? If not then it is probably an "incompatibility" between 2 mods, or at least with a mod that changes the behavior of chunks. (In which case I'm sorry but I won't narrow it down to the 2 mods causing the issue; however if you find them I can investigate further).

As your stack trace shows MC is hanging inside a Minecraft function that I just call to obtain a chunk.

**Comment by TelepathicGrunt** [comment]
I only loaded the modpack to test out my own Bumblezone mod to see how it interacted with others so I'm not really a player that's playing the modpack heavily. I saw this issue as I was testing and only posted it here in passing just to let you know so you can investigate if you wish.

I did go back and tried removing mods but was ultimately unsuccessful to finding what other mod could be involved. Your mod does work alone. I won't spend more time on this as I have my own mods to work on and not much free time. 

What I will say, judging from your code, the fact it is running at the end of server tick on the server thread means your code is not running during worldgen. Thus this is not a case of worldgen code calling the serverworld methods which would've been a deadlock. Maybe falling leaves is trying to load a chunk that isn't yet generated, the chunk goes to offthread to be generated, and that thread crashes leaving the server thread stuck. But I would've expected something in the log about the crashed thread...

You can close this if you wish and don't want to look into it.

**Comment by Rakambda** [comment]
For traceability this is where it guess it gets stuck:

```java
// net/minecraft/server/level/ServerChunkCache.class:118
if (Thread.currentThread() != this.mainThread) {
    return (ChunkAccess)CompletableFuture.supplyAsync(() -> {
        return this.getChunk(i, j, chunkStatus, bl);
    }, this.mainThreadProcessor).join();
}
```

Not sure I can do anything about this. I'll close this issue for now and will investigate more if more people encounter it.

**Comment by embeddedt** [comment]
This is still an issue. I am using 1.16 so it is possible the 1.19 code is structured differently, but in 1.16 it appears that you do not clear the list of scheduled leaf ticks when a world is closed. This means that when the next world starts ticking your code starts trying to process leaf ticks for an old world, and therefore chunkloading never completes on it.

The solution is to, quite simply, not be interacting with data for an already closed world. :)

**Comment by Rakambda** [comment]
Can you try with this build and see if it changes anything? (for forge 1.16.5)
[FallingTree-1.16.5-2.11.6.zip](https://github.com/Rakambda/FallingTree/files/11221393/FallingTree-1.16.5-2.11.6.zip) (mod is inside the zip file)

**Comment by embeddedt** [comment]
The issue appears to be fixed with this new version. Tested by entering a world, breaking the logs of a tree, and immediately saving and quitting before the leaves can finish decaying. In the old version this consistently causes reloading the world to freeze at 100%, with the profiler showing a frozen attempt to process leaf ticks. In the new version the world reloads properly.

**Comment by Rakambda** [comment]
Great. I'll have to see to have a similar fix for the fabric version as well as porting it to newer versions.
Though for now I don't have much free time so it may take some time. As this isn't a critical issue it should be fine. You can use the test version in the meantime.
