### ISSUE TITLE
Mod is not server-side only

### ISSUE THREAD

**Issue by Lauriichan** [RakambdaOrg/FallingTree#581]
### Describe the bug

The client crashes once you try to cut a tree.
Even if you set the speedMultiplicand to 0 it still crashes probably because a packet channel is registered and used while the forge client doesn't know about that channel and crashes because of it.

### Minecraft version

1.20.1

### Forge version

47.1.0

### Mod version

4.2.4

### Relevant log output

```shell
[10:08:54] [Render thread/ERROR]: Exception caught during firing event: Registry Object not present: fallingtree:chopper
	Index: 6
	Listeners:
		0: HIGH
		1: net.minecraftforge.eventbus.EventBus$$Lambda$1667/0x00000008013ff2d0@3cd4b442
		2: NORMAL
		3: ASM: net.orcinus.galosphere.events.MobEvents@5c033c6d onBreakSpeedChanged(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
		4: ASM: class tschipp.carryon.events.CommonEvents harvestSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
		5: ASM: class quek.undergarden.item.tool.UGToolEvents forgottenDigEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
		6: ASM: fr.rakambda.fallingtree.forge.event.BlockBreakListener@2e65caf5 onBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$1667/0x00000008013ff2d0@4ef64674
		8: ASM: me.desht.pneumaticcraft.common.event.PneumaticArmorHandler@37814baf breakSpeedCheck(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
		9: LOW
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1667/0x00000008013ff2d0@726d7640
java.lang.NullPointerException: Registry Object not present: fallingtree:chopper
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at TRANSFORMER/forge@47.1.0/net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.forge.common.wrapper.EnchantmentWrapper.getRaw(EnchantmentWrapper.java:22)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.forge.common.wrapper.EnchantmentWrapper.getRaw(EnchantmentWrapper.java:13)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.forge.common.wrapper.ItemStackWrapper.getAnyEnchant(ItemStackWrapper.java:88)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.common.tree.TreeHandler.getBreakMode(TreeHandler.java:77)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.common.tree.TreeHandler.getBreakSpeed(TreeHandler.java:98)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.forge.event.BlockBreakListener.onBreakSpeed(BlockBreakListener.java:37)
	at TRANSFORMER/fallingtree@4.2.4/fr.rakambda.fallingtree.forge.event.__BlockBreakListener_onBreakSpeed_BreakSpeed.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.1.0/net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:187)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.getDigSpeed(Player.java:721)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour.m_5880_(BlockBehaviour.java:370)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(MixinBlockStateBase.java:641)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.lambda$startDestroyBlock$1(MultiPlayerGameMode.java:166)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105269_(MultiPlayerGameMode.java:157)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1632)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1972)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[10:08:54] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Registry Object not present: fallingtree:chopper
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.20.1-47.1.0-universal.jar%23477!/:?]
	at fr.rakambda.fallingtree.forge.common.wrapper.EnchantmentWrapper.getRaw(EnchantmentWrapper.java:22) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at fr.rakambda.fallingtree.forge.common.wrapper.EnchantmentWrapper.getRaw(EnchantmentWrapper.java:13) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at fr.rakambda.fallingtree.forge.common.wrapper.ItemStackWrapper.getAnyEnchant(ItemStackWrapper.java:88) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at fr.rakambda.fallingtree.common.tree.TreeHandler.getBreakMode(TreeHandler.java:77) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at fr.rakambda.fallingtree.common.tree.TreeHandler.getBreakSpeed(TreeHandler.java:98) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at fr.rakambda.fallingtree.forge.event.BlockBreakListener.onBreakSpeed(BlockBreakListener.java:37) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at fr.rakambda.fallingtree.forge.event.__BlockBreakListener_onBreakSpeed_BreakSpeed.invoke(.dynamic) ~[FallingTree-1.20.1-4.2.4.jar%23378!/:4.2.4]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:187) ~[forge-1.20.1-47.1.0-universal.jar%23477!/:?]
	at net.minecraft.world.entity.player.Player.getDigSpeed(Player.java:721) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour.m_5880_(BlockBehaviour.java:370) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(MixinBlockStateBase.java:641) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.lambda$startDestroyBlock$1(MultiPlayerGameMode.java:166) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105269_(MultiPlayerGameMode.java:157) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1632) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1972) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[10:08:55] [Render thread/INFO]: Minimap session finalized.
[10:08:55] [Render thread/INFO]: Finalizing world map session...
[10:08:55] [Thread-15/INFO]: World map cleaned normally!
[10:08:56] [Render thread/INFO]: World map session finalized.
[10:08:56] [Render thread/INFO]: Disconnected from server, resetting proxy config values
[10:08:56] [Render thread/INFO]: Released client Flux Networks cache
[10:08:56] [Render thread/INFO]: Curios disabled
[10:08:56] [Render thread/INFO]: Removed all colony views
[10:08:56] [Render thread/INFO]: Stopping worker threads
[10:08:57] [Render thread/FATAL]: Preparing crash report with UUID 8ce71cac-813e-44ef-8449-93b2380561af
[10:08:57] [Render thread/FATAL]: Preparing crash report with UUID 7c127102-a1df-4dd8-8b44-b070ee38f4f4
```

**Comment by Lauriichan** [comment]
The wiki also doesn't explain how you would disable the speed change feature specifically therefore I don't really know how I should use this mod without telling my uses to install it which I don't want to do when it comes to using a public modpack that receives updates

**Comment by Lauriichan** [comment]
I just found out the mod is indeed installed on the client.
