### ISSUE TITLE
Consol error and game crash

### ISSUE THREAD

**Issue by askarYT** [RakambdaOrg/FallingTree#584]
### Describe the bug

Hey !

I have launched a server with my friend for a survival party and when we have played after some times our game crash. Not the server juste the game client-side.

I have tried launch the server mod by mod and when i launched with your mod i have this error in my consol.

> Forge 1.18.2 | 40.2.0
> Mod version 3.5.5, 3.5.4, 3.5.3 (not tested older version just this tree)
> Error : 

![image](https://github.com/Rakambda/FallingTree/assets/77925827/67abb2bd-3e48-454d-bbbf-47933982ed1b)

Any idea how to fix it ? 

### Minecraft version

1.18.2

### Forge version

40.2.0

### Mod version

3.5.5 and older

### Configuration

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false
  },
  "sneakMode": "SNEAK_DISABLE",
  "breakInCreative": false,
  "notificationMode": "ACTION_BAR"
}
```

### Relevant log output

```shell
[21août2023 14:09:49.379] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cgm] Found status: BETA Current: 1.3.3 Target: 1.3.3
[21août2023 14:09:49.379] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Starting version check at https://mrcrayfish.com/modupdatejson?id=cfm
[21août2023 14:09:49.682] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Found status: BETA Current: 7.0.0-pre35 Target: 7.0.0-pre35
[21août2023 14:09:49.683] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [framework] Starting version check at https://mrcrayfish.com/modupdatejson?id=framework
[21août2023 14:09:49.982] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [framework] Found status: BETA Current: 0.4.3 Target: 0.4.3
[21août2023 14:09:49.982] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [fallingtree] Starting version check at https://raw.githubusercontent.com/wiki/RakSrinaNa/FallingTree/assets/update.json
[21août2023 14:09:50.101] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2320!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2320!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2320!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2320!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.18.2-40.2.0.jar%2362!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.18.2-40.2.0.jar%2362!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%2320!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%2320!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2320!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2320!/:?]
	... 6 more
[21août2023 14:09:50.102] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[21août2023 14:09:50.432] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 40.2.0 Target: null
[21août2023 14:09:50.432] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [flywheel] Starting version check at https://api.modrinth.com/updates/5lpsZoRi/forge_updates.json
[21août2023 14:09:50.617] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [flywheel] Found status: AHEAD Current: 0.6.8-97 Target: null
[21août2023 14:09:50.617] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [gravestone] Starting version check at https://maxhenkel.de/update/gravestone.json
```

**Comment by askarYT** [comment]
*Edit : I tried to play without your mod and the game always crash client-side, idk why 🤔

**Comment by Rakambda** [comment]
Hello, this isn't a crash. This is just a WARN message from the forge version checker saying it can't get the data.
I have deleted [the file](https://raw.githubusercontent.com/wiki/RakSrinaNa/FallingTree/assets/update.json) since quite a while.

However this doesn't make forge crash, the real issue should be further down the logs.

**Comment by askarYT** [comment]
Hmm, ok sorry for the inconvenience then. I'll try to investigate what is causing me to crash the game then :)
Idk why it's crash but it is painful

**Comment by Rakambda** [comment]
The error is probably at the end of the log file of the client after it crashes.

**Comment by askarYT** [comment]
I checked the log and debug files on my client and there is nothing that says where the error comes from (or just I'm blind but yet...)

Thank you anyway and sorry for the inconvenience in this case :)
I thought the console error was some kind of bug since it puts all other messages in red even when joining and leaving the server
