### ISSUE TITLE
Mod failed to load correctly with latest version of Forge

### ISSUE THREAD

**Issue by neito7** [RakambdaOrg/FallingTree#599]
### Describe the bug

I tried to load this mod with the latest version of forge and got the following error message:

![Screenshot_1](https://github.com/RakambdaOrg/FallingTree/assets/145616342/1e3a3f94-c359-4c99-80a1-984f220543ed)

### Minecraft version

1.19.2

### Forge version

43.2.23

### Mod version

3.10.0

### Configuration

```json
# Configuration file

general {
    # When set to true, the mod will cut down trees in creative too.
    B:break_in_creative=false

    # When set to true, a tree will only be chopped down if the player is sneaking.
    B:reverse_sneaking=false
}


tools {
    # List of tools that should not be considered as tools.
    # INFO: This wins over the whitelist.
    S:blacklisted <
     >

    # Defines the number of times the damage is applied to the tool.
    # ie: if set to 1 then breaking 5 logs will give 5 damage.
    # ie: if set to 2 then breaking 5 logs will give 10 damage.
    # If set to 0, it'll still apply 1 damage for every cut.
    # INFO: This only applies when the tree is cut when using the mod.
    # Min: 0
    # Max: 2147483647
    I:damage_multiplicand=1

    # When set to true, the mod will be activated no matter what you have in your hand (or empty hand).
    # INFO: Blacklist still can be use to restrict some tools.
    B:ignore_tools=false

    # When set to true, when a tree is broken and the tool is about to break we will just break enough blocks so that the tool is left at 1 of durability.
    B:preserve=false

    # Applies a speed modifier when breaking the tree.
    # 0 will disable this, so the speed will be the default one of breaking a block.
    # If set to 1 each log block will be counted once, so if the tree is 5 blocks tall it'll require the time of breaking 5 logs.
    # If set to 2 each log block will be counted twice, so if the tree is 5 blocks tall, it'll require the time of breaking 10 logs
    # INFO: Only in INSTANTANEOUS mode.
    # WARNING: If you are on a server, this either has to be set to 0 or every player should have the mod. Else they'll have a weird effect of breaking the block but the block is still there.
    # Min: 0.0
    # Max: 50.0
    D:speed_multiplicand=0.0

    # Additional list of tools that can be used to chop down a tree.
    # INFO: Items marked with the axe tag will already be whitelisted.
    S:whitelisted <
     >
}


trees {
    # When set to true this allow to have any kind of log in a tree trunk.
    # Otherwise (false) the trunk will be considered as being only one kind of log.
    B:allow_mixed_logs=false

    # How to break the tree.
    # Instantaneous will break it in one go.
    # Shift down will make the tree fall down as you cut it, so you still have to break x blocks but don't have to climb the tree for them.
    # Valid values:
    # INSTANTANEOUS
    # SHIFT_DOWN
    S:break_mode=INSTANTANEOUS

    # List of blocks that should not be considered as leaves.
    # INFO: This wins over the whitelist.
    S:leaves_blacklisted <
     >

    # When set to true, leaves that should naturally break will be broken instantly.
    B:leaves_breaking=true

    # Radius to force break leaves. If another tree is still holding the leaves they'll still be broken. If the leaves are persistent (placed by player) they'll also be destroyed.
    # The radius is applied from one of the top most log blocks.
    # INFO: break_leaves must be activated for this to take effect.
    # INFO: Only in INSTANTANEOUS mode.
    # Min: 0
    # Max: 10
    I:leaves_breaking_force_radius=0

    # Additional list of blocks considered as leaves.
    # INFO: Blocks marked with the leaves tag will already be whitelisted.
    S:leaves_whitelisted <
     >

    # List of blocks that should not be considered as logs.
    # INFO: This wins over the whitelist.
    S:logs_blacklisted <
     >

    # The maximum size of a tree. If there's more logs than this value the tree won't be cut.
    # INFO: Only in INSTANTANEOUS mode.
    # Min: 1
    # Max: 2147483647
    I:logs_max_count=100

    # Additional list of blocks considered as logs and that will be destroyed by the mod.
    # INFO: Blocks marked with the log tag will already be whitelisted.
    S:logs_whitelisted <
     >

    # The minimum amount of leaves that needs to be around the top most log in order for the mod to consider it a tree.
    # INFO: Only in INSTANTANEOUS mode.
    # Min: 0
    # Max: 5
    I:minimum_leaves_around_required=0
}
```

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-09-20 18:25:22
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.23-universal.jar%23242!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.23-universal.jar%23242!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.23.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%23127!/:?] {}
-- MOD fallingtree --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.23.jar%23239!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.23.jar%23238!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.9.jar%23127!/:?] {}
		at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23127!/:?] {}
		at com.google.gson.Gson.fromJson(Gson.java:901) ~[gson-2.8.9.jar%23127!/:?] {}
		at fr.raksrinana.fallingtree.common.config.real.ConfigLoader.loadConfig(ConfigLoader.java:22) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
		at fr.raksrinana.fallingtree.common.config.real.Configuration.read(Configuration.java:46) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
		at fr.raksrinana.fallingtree.common.FallingTreeCommon.<init>(FallingTreeCommon.java:42) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
		at fr.raksrinana.fallingtree.forge.common.FallingTreeCommonsImpl.<init>(FallingTreeCommonsImpl.java:63) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
		at fr.raksrinana.fallingtree.forge.FallingTree.<clinit>(FallingTree.java:18) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.23.jar%23239!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.23.jar%23238!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/matia/AppData/Roaming/.minecraft/mods/FallingTree-1.19.2-3.10.0.jar
	Failure message: FallingTree (fallingtree) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 3.10.0
	Mod Issue URL: https://github.com/RakSrinaNa/FallingTree/issues
	Exception message: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Stacktrace:
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:901) ~[gson-2.8.9.jar%23127!/:?] {}
	at fr.raksrinana.fallingtree.common.config.real.ConfigLoader.loadConfig(ConfigLoader.java:22) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
	at fr.raksrinana.fallingtree.common.config.real.Configuration.read(Configuration.java:46) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
	at fr.raksrinana.fallingtree.common.FallingTreeCommon.<init>(FallingTreeCommon.java:42) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
	at fr.raksrinana.fallingtree.forge.common.FallingTreeCommonsImpl.<init>(FallingTreeCommonsImpl.java:63) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
	at fr.raksrinana.fallingtree.forge.FallingTree.<clinit>(FallingTree.java:18) ~[FallingTree-1.19.2-3.10.0.jar%23209!/:3.10.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.23.jar%23239!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.23.jar%23238!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 401305216 bytes (382 MiB) / 838860800 bytes (800 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 520
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2115
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 10412.91
	Virtual memory used (MB): 7288.24
	Swap memory total (MB): 2304.00
	Swap memory used (MB): 406.30
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |13.0.14             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19.2-2.0.1.166.jar           |TerraBlender                  |terrablender                  |2.0.1.166           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.44-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.44       |COMMON_SET|Manifest: NOSIGNATURE
		blue_skies-1.19.2-1.3.20.jar                      |Blue Skies                    |blue_skies                    |1.3.20              |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.1.162.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.162          |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.9.0.jar                       |Jade                          |jade                          |8.9.0               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.3_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1015.jar                  |Just Enough Items             |jei                           |11.6.0.1015         |COMMON_SET|Manifest: NOSIGNATURE
		CookingwithMindthemoodsV8.1.jar                   |Cooking with Mindthemoods     |cooking_with_mindthemoods     |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.2-1.0.20.jar         |Resourcefulconfig             |resourcefulconfig             |1.0.20              |COMMON_SET|Manifest: NOSIGNATURE
		dungeons_enhanced-1.19.2-4.1.jar                  |Dungeons Enhanced             |dungeons_enhanced             |4.1                 |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.19.2-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		goblintraders-1.8.0-1.19.2.jar                    |Goblin Traders                |goblintraders                 |1.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		Incendium_1.19.3_v5.1.6.jar                       |Incendium                     |incendium                     |5.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.87.417.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.87.417   |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.19.2-7.3.2.jar                          |Placebo                       |placebo                       |7.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.29-1.19.2.jar                |Cataclysm Mod                 |cataclysm                     |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		bettervillage-forge-1.19.2-3.1.0.jar              |Better village                |bettervillage                 |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Gobber2-Forge-1.19.2-2.7.28.jar                   |Gobber 2                      |gobber2                       |2.7.28              |COMMON_SET|Manifest: NOSIGNATURE
		tombstone-8.2.9-1.19.2.jar                        |Corail Tombstone              |tombstone                     |8.2.9               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.3.20.jar                |Bookshelf                     |bookshelf                     |16.3.20             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.19.2-3.18.55.889.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.55.889  |COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre35-1.19.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre35         |COMMON_SET|Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.6.6_mc1.19.2.jar              |ItemPhysic                    |itemphysic                    |1.6.6               |COMMON_SET|Manifest: NOSIGNATURE
		The_Undergarden-1.19.2-0.8.3.jar                  |The Undergarden               |undergarden                   |0.8.3               |COMMON_SET|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.19.2-2.1.jar                  |FPS Reducer                   |fpsreducer                    |1.19.2-2.1          |COMMON_SET|Manifest: NOSIGNATURE
		framework-forge-1.19.2-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		FallingTree-1.19.2-3.10.0.jar                     |FallingTree                   |fallingtree                   |3.10.0              |ERROR     |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		cloth-config-8.2.84-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.84              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.23-universal.jar                |Forge                         |forge                         |43.2.23             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        |Towns and Towers              |t_and_t                       |1.10                |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		creeperoverhaul-2.0.9-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |2.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.19.2-2.7.2.jar                    |Structure Gel API             |structure_gel                 |2.7.2               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 5da2c3c9-2f12-4e21-9c93-74869cd2944e
	FML: 43.2
	Forge: net.minecraftforge:43.2.23
```

**Comment by Rakambda** [comment]
Configuration file is supposed to be JSON, what you show is TOML (or whatever forge was using at the time). 
If you come from an old forge version, I suggest you to let the mod create the fallingtree.json, and the edit it.

**Comment by neito7** [comment]
How do I open the .json file? When I try to open it with notepad, it has nothing inside.
![image](https://github.com/RakambdaOrg/FallingTree/assets/145616342/0d175781-1278-4013-a57e-c107b808c12e)
![image](https://github.com/RakambdaOrg/FallingTree/assets/145616342/fc784fe4-0ecb-4485-84f5-cfbf072ccff0)

**Comment by Rakambda** [comment]
Notepad should be fine. It shouldn't be empty though.
Try to delete it, the mod should create it again properly at startup.

**Comment by neito7** [comment]
I deleted the .json and now it works, thank for your help :D
