### ISSUE TITLE
Attempted to send invalid message fr.rakambda.fallingtree.common.config.proxy.ProxyConfiguration on channel fallingtree:main

### ISSUE THREAD

**Issue by MoseySauce** [RakambdaOrg/FallingTree#611]
### Describe the bug

I have created a brand new Forge Server and added a number of mods.  After adding FallingTree mod, I can no longer log into the server with an Invalid Player Data error message.  I have attached the logged stack trace from the server.  I have the mod installed on both my server and my client.  I don't know if makes a difference, but my player does spawn on top of a very large tree when FallingTree is removed.

### Minecraft version

1.20.2

### Forge version

1.20.2-48.0.30

### Mod version

1.20.2-5.0.1

### Configuration

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "breakMangroveRoots": true,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0,
    "forceToolUsage": false
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false,
    "requireEnchantment": false
  },
  "sneakMode": "SNEAK_DISABLE",
  "breakInCreative": false,
  "lootInCreative": true,
  "notificationMode": "ACTION_BAR"
}
```

### Relevant log output

```shell
[16:46:39] [Server thread/INFO] [minecraft/MinecraftServer]: _MoseySauce joined the game
[16:46:39] [Server thread/ERROR] [ne.mi.ne.SimpleChannel/SIMPLE_CHANNEL]: Attempted to send invalid message fr.rakambda.fallingtree.common.config.proxy.ProxyConfiguration on channel fallingtree:main
[16:46:39] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Invalid message fr.rakambda.fallingtree.common.config.proxy.ProxyConfiguration
	Index: 4
	Listeners:
		0: NORMAL
		1: ASM: xaero.map.events.CommonEvents@5cc3c20a onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: ASM: xaero.common.events.ForgeCommonEventHandler@c512c3f onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$4641/0x00007f9cdcaa8250@5bec0930
		4: ASM: fr.rakambda.fallingtree.forge.network.PlayerJoinListener@66534aa1 onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: ASM: net.minecraftforge.common.ForgeInternalHandler@5a4edcb1 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: Invalid message fr.rakambda.fallingtree.common.config.proxy.ProxyConfiguration
	at TRANSFORMER/forge@48.0.30/net.minecraftforge.network.SimpleChannel.toBuffer(SimpleChannel.java:342)
	at TRANSFORMER/forge@48.0.30/net.minecraftforge.network.Channel.send(Channel.java:82)
	at TRANSFORMER/fallingtree@5.0.1/fr.rakambda.fallingtree.forge.network.PlayerJoinListener.onPlayerLoggedInEvent(PlayerJoinListener.java:29)
	at TRANSFORMER/fallingtree@5.0.1/fr.rakambda.fallingtree.forge.network.__PlayerJoinListener_onPlayerLoggedInEvent_PlayerLoggedInEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@48.0.30/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:170)
	at TRANSFORMER/forge@48.0.30/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:695)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:244)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.m_293007_(ServerConfigurationPacketListenerImpl.java:125)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.m_5797_(ServerboundFinishConfigurationPacket.java:20)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.m_5797_(ServerboundFinishConfigurationPacket.java:7)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:160)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:660)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249)
	at java.base/java.lang.Thread.run(Thread.java:833)

[16:46:39] [Server thread/ERROR] [minecraft/ServerConfigurationPacketListenerImpl]: Couldn't place player in world
java.lang.IllegalArgumentException: Invalid message fr.rakambda.fallingtree.common.config.proxy.ProxyConfiguration
	at net.minecraftforge.network.SimpleChannel.toBuffer(SimpleChannel.java:342) ~[forge-1.20.2-48.0.30-universal.jar%23120!/:?]
	at net.minecraftforge.network.Channel.send(Channel.java:82) ~[forge-1.20.2-48.0.30-universal.jar%23120!/:?]
	at fr.rakambda.fallingtree.forge.network.PlayerJoinListener.onPlayerLoggedInEvent(PlayerJoinListener.java:29) ~[FallingTree-1.20.2-5.0.1.jar%23108!/:5.0.1]
	at fr.rakambda.fallingtree.forge.network.__PlayerJoinListener_onPlayerLoggedInEvent_PlayerLoggedInEvent.invoke(.dynamic) ~[FallingTree-1.20.2-5.0.1.jar%23108!/:5.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2350!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2350!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2350!/:?]
	at net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:170) ~[forge-1.20.2-48.0.30-universal.jar%23120!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:695) ~[forge-1.20.2-48.0.30-universal.jar%23120!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:244) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.m_293007_(ServerConfigurationPacketListenerImpl.java:125) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.m_5797_(ServerboundFinishConfigurationPacket.java:20) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.m_5797_(ServerboundFinishConfigurationPacket.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:160) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:660) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[server-1.20.2-20230921.100330-srg.jar%23115!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:46:39] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: _MoseySauce lost connection: Invalid player data
[16:46:39] [Server thread/INFO] [minecraft/MinecraftServer]: _MoseySauce left the game
```

**Comment by Rakambda** [comment]
This seems to be more an issue with the mod itself and not something that you do wrong.
I'll try to take a look at it tomorrow.
