### ISSUE TITLE
Chopping down a tree in Shoulder Surfing Reloaded perspective crashes the game

### ISSUE THREAD

**Issue by Snooziepup** [RakambdaOrg/FallingTree#703]
### Describe the bug

When attempting to chop down a tree using any treechop type, if the player is in the perspective mode added in Shoulder Surfing Reloaded, the game will crash.

### Minecraft version

1.21

### Fabric API version

0.100.3

### Mod version

1.21.0.1

### Configuration

```json
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "WHOLE_TREE",
    "maxScanSize": 500,
    "maxSize": 100,
    "maxLeafDistanceFromLog": 15,
    "maxSizeAction": "ABORT",
    "breakOrder": "FURTHEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "breakMangroveRoots": true,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": true,
    "ignoreTools": false,
    "damageMultiplicand": 1.0,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.0,
    "forceToolUsage": false
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "requireEnchantment": false
  },
  "sneakMode": "SNEAK_DISABLE",
  "breakInCreative": false,
  "lootInCreative": true,
  "notificationMode": "ACTION_BAR"
}
```

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-06-18 23:45:24
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zjj000$continuity$beforeRenderModel(class_901.java:515)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zjj000$continuity$beforeRenderModel(class_901.java:515)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 624
	Entity Name: Falling Oak Log
	Entity's Exact location: -326.83, 82.46, -821.04
	Entity's Block location: World: (-327,82,-822), Section: (at 9,2,10 in -21,5,-52; chunk contains blocks -336,-64,-832 to -321,319,-817), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Entity's Momentum: 0.17, -0.04, -0.04
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:oak_log}[axis=y]
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@61f6247c
	Location: 4.70,1.55,3.03 - World: (4,1,3), Section: (at 4,1,3 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 0.28001595
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 115.381s
	Wall uptime: 100.338s
	High-res time: 94.629s
	Client ticks: 1641 ticks / 82.050s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['Snooziepup'/12, l='ClientLevel', x=-329.12, y=78.00, z=-823.18]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,71,-480), Section: (at 0,7,0 in -14,4,-30; chunk contains blocks -224,-64,-480 to -209,319,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 121914 game time, 121914 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 170

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, continuity:default, continuity:glass_pane_culling_fix, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip, file/Icons v.1.11.1.zip, fabric, appleskin, auditory, balm-fabric, betterbeds, betterstats, buildguide, caffeineconfig, chesttracker, chunksfadein, chunky, clean-debug, clienttweaks, cloth-config, continuity, craftingtweaks, detailab, dynamic_fps, eatinganimationid, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabrishot, fallingtree, forgeconfigapiport, freecam, hiddenrecipebook, idwtialsimmoedm, image2map, immediatelyfast, infinite-music, inventoryprofilesnext, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jade, jei, libipn, lithium, logbegone, midnightlib, modernfix, modmenu, nochatreports, notenoughanimations, packetfixer, paginatedadvancements, peek, reeses-sodium-options, resourcify, searchables, sit, sodium, sodium-extra, spyglass_improvements, status-effect-bars, tcdcommons, third_person_maps, voicechat, whereisit, xaerominimap, xaeroworldmap, xaerozoomout, yet_another_config_lib_v3, minecraft:supporteatinganimation

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 376209440 bytes (358 MiB) / 1022361600 bytes (975 MiB) up to 5389680640 bytes (5140 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 22514.56
	Virtual memory used (MiB): 11236.91
	Swap memory total (MiB): 15000.00
	Swap memory used (MiB): 507.16
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 18848.66, total: 122880.00
	Space in storage for workdir (MiB): available: 18848.66, total: 122880.00
	JVM Flags: 10 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8m -Xmx5140m
	Fabric Mods: 
		appleskin: AppleSkin 3.0.2+mc1.21
		audioplayer: AudioPlayer 1.21-1.10.2
			admiral: Admiral 0.4.4+1.20.5
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
		auditory: Auditory 0.0.7-1.21
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 21.0.7
			kuma_api: KumaAPI 21.0.4
		betterbeds: Better Beds 1.4.0
		betterstats: Better Statistics Screen 3.11.1+fabric-1.21
		buildguide: Build Guide 0.4.1
		chesttracker: Chest Tracker 2.4.7+1.21
			whereisit: Where Is It 2.5.0+1.21
				jackfredlib: JackFredLib 0.10.0+1.21
					jackfredlib-base: JackFredLib: Base 1.4.0+1.21
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21
					jackfredlib-toasts: JackFredLib: Toasts 1.1.0+1.21
		chunksfadein: Chunks Fade In 1.0.0-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		chunky: Chunky 1.4.16
		clean-debug: Clean F3 0.4.5
		clienttweaks: Client Tweaks 21.0.2
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.1
		collective: Collective 7.61
		continuity: Continuity 3.0.0-beta.5+1.21
		craftingtweaks: Crafting Tweaks 21.0.3
		cyclepaintings: Cycle Paintings 3.5
		detailab: Detail Armor Bar 2.6.3+1.21-fabric
		doubledoors: Double Doors 5.8
		dynamic_fps: Dynamic FPS 3.4.3
		eatinganimationid: Eating Animation 1.21+1.9.71
		entity_model_features: Entity Model Features 2.1
		entity_texture_features: Entity Texture Features 6.1.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.3+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.13+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.14+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.1+8a3b5617d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.23+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.8+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.1+cb5ced13d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.10+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.11+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.9+6573ed8cd1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.22+ab7edbacd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6bd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.4+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d1321076d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.4+cb5ced13d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.79+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.14+b5597344d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fabrishot: Fabrishot 1.14.0
		fallingtree: FallingTree 1.21.0.1
		ferritecore: FerriteCore 7.0.0
		fishontheline: Fish On The Line 3.3
		forgeconfigapiport: Forge Config API Port 21.0.0
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		freecam: Freecam (Modrinth Edition) 1.3.0-beta1+mc1.21
		guiclock: GUI Clock 4.5
		guicompass: GUI Compass 4.7
		hiddenrecipebook: Hidden Recipe Book 4.6
		idwtialsimmoedm: idwtialsimmoedm 0.3.0+1.21
		image2map: Image2Map 0.7.0+1.21
			map-canvas-api: Map Canvas API 0.4.0+1.21
			sgui: sgui 1.6.0+1.21
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		infinite-music: Infinite Music 0.4.3
		inventoryprofilesnext: Inventory Profiles Next 2.0.0
		jade: Jade 15.0.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.0.0.3
		justplayerheads: Just Player Heads 4.0
		letmedespawn: Let Me Despawn 1.3.0
		libipn: libIPN 5.0.0
		lithium: Lithium 0.12.5
		logbegone: Log Begone 1.0.2
		midnightlib: MidnightLib 1.5.7
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.18.2+mc1.21
		modmenu: Mod Menu 11.0.0
		mousetweaks: Mouse Tweaks 2.26
		nochatreports: No Chat Reports 1.21-v2.8.0
		notenoughanimations: NotEnoughAnimations 1.7.4
		packetfixer: Packet Fixer 1.4.1
		paginatedadvancements: Paginated Advancements 2.4.2
		peek: Peek 1.21-1.3.2
		placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		quickrightclick: Quick Right-Click 1.4
		railoptimization: RailOptimization 1.2
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		replantingcrops: Replanting Crops 5.3
		resourcefullib: Resourceful Lib 3.0.0
			com_teamresourceful_bytecodecs: bytecodecs 1.1.0
			com_teamresourceful_yabn: yabn 1.0.3
		resourcify: Resourcify 1.4.0
			universalcraft: UniversalCraft 342
		searchables: Searchables 1.0.1
		shouldersurfing: Shoulder Surfing Reloaded 4.1.4
		sit: Sit 1.21-28
		sodium: Sodium 0.5.9+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		spyglass_improvements: Spyglass Improvements 1.5.3
		status-effect-bars: Status Effect Bars 1.0.6
		tcdcommons: TCD Commons API 3.11+fabric-1.21
		third_person_maps: Third Person Maps 1.5.3
		voicechat: Simple Voice Chat 1.21-2.5.17
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		xaerozoomout: XaeroZoomout 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.21
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 1920x1080
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/10 chunks
	Resource Packs: vanilla, continuity:default, continuity:glass_pane_culling_fix, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip, file/Icons v.1.11.1.zip, fabric, appleskin (incompatible), auditory, balm-fabric (incompatible), betterbeds, betterstats, buildguide, caffeineconfig, chesttracker, chunksfadein, chunky, clean-debug, clienttweaks (incompatible), cloth-config, continuity, craftingtweaks (incompatible), detailab, dynamic_fps, eatinganimationid, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabrishot, fallingtree, forgeconfigapiport, freecam, hiddenrecipebook (incompatible), idwtialsimmoedm, image2map, immediatelyfast, infinite-music, inventoryprofilesnext, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jade (incompatible), jei (incompatible), libipn, lithium, logbegone, midnightlib, modernfix (incompatible), modmenu, nochatreports, notenoughanimations, packetfixer (incompatible), paginatedadvancements, peek, reeses-sodium-options, resourcify (incompatible), searchables (incompatible), sit, sodium, sodium-extra, spyglass_improvements, status-effect-bars, tcdcommons, third_person_maps, voicechat, whereisit, xaerominimap (incompatible), xaeroworldmap (incompatible), xaerozoomout (incompatible), yet_another_config_lib_v3 (incompatible), minecraft:supporteatinganimation
	Current Language: en_us
	Locale: en_GB
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 5500U with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Snooziepup'/12, l='ServerLevel[gooba gooba]', x=-329.12, y=78.00, z=-823.18]]
	Active Data Packs: vanilla, fabric, audioplayer, auditory, balm-fabric (incompatible), collective, craftingtweaks (incompatible), fabric-convention-tags-v2, spyglass_improvements
	Available Data Packs: audioplayer, auditory, balm-fabric (incompatible), bundle, collective, craftingtweaks (incompatible), fabric, fabric-convention-tags-v2, spyglass_improvements, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -5927254688842149212
```

**Comment by Rakambda** [comment]
Hmm, the error does happen in FallingTree, it seems to happen in something called continuity.

It seems to happen when there's a falling block. However FallingTtee does nothing special about it, it's the same thing as falling sand/gravel.

**Comment by Rakambda** [comment]
https://github.com/PepperCode1/Continuity/issues/436
