### ISSUE TITLE
New version 2.11.1 (unified fabric+forge) crashes on load

### ISSUE THREAD

**Issue by MeeniMc** [RakambdaOrg/FallingTree#94]
**Describe the bug**
Dedicated server crashes on load. 
It works fine on singleplayer.

**To Reproduce**
1. switch mod from 2.10.0 to 2.11.1
2. launch dedicated server
3. crashes with error `this.config is null` in autoconfig

**Infos:**
 - Minecraft version: 1.16.5
 - Mod version: 2.11.1 (autoconfig1u@3.3.1)
 - Fabric version: 0.11.3

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

```
[09:41:32] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fallingtree'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[77e1f401-7045-46a4-a767-2ee3fcc39697.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[77e1f401-7045-46a4-a767-2ee3fcc39697.jar:?]
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[77e1f401-7045-46a4-a767-2ee3fcc39697.jar:?]
	at fr.raksrinana.fallingtree.fabric.config.Configuration.register(Configuration.java:52) ~[FallingTree-1.16.5-2.11.1.jar:?]
	at fr.raksrinana.fallingtree.fabric.FallingTree.onInitialize(FallingTree.java:14) ~[FallingTree-1.16.5-2.11.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
```

**Comment by Rakambda** [comment]
I can't reproduce it.

```
[16:50:11] [main/INFO]: Loading for game Minecraft 1.16.5
[16:50:11] [main/INFO]: [FabricLoader] Loading 50 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@16, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.5+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.11.19, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fallingtree@2.11.1, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.5+351679a77d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[16:50:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/Minecraft/test/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[16:50:16] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:50:16] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[16:50:16] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:50:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:50:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:50:16] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:50:16] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:50:16] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[16:50:17] [Worker-Main-10/INFO]: Loaded 7 recipes
[16:50:17] [Worker-Main-10/INFO]: Loaded 927 advancements
[16:50:18] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 1.102 ms
[16:50:18] [Server thread/INFO]: Starting minecraft server version 1.16.5
[16:50:18] [Server thread/INFO]: Loading properties
[16:50:18] [Server thread/INFO]: Default game type: SURVIVAL
[16:50:18] [Server thread/INFO]: Generating keypair
[16:50:18] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:50:18] [Server thread/INFO]: Using default channel type
[16:50:19] [Server thread/INFO]: Preparing level "world"
[16:50:19] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:50:20] [Server thread/INFO]: Preparing spawn area: 0%
[16:50:20] [Server thread/INFO]: Preparing spawn area: 0%
[16:50:21] [Server thread/INFO]: Preparing spawn area: 0%
[16:50:21] [Server thread/INFO]: Preparing spawn area: 0%
[16:50:23] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[16:50:23] [Worker-Main-17/INFO]: Preparing spawn area: 83%
[16:50:23] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[16:50:23] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[16:50:23] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[16:50:24] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[16:50:24] [Worker-Main-8/INFO]: Preparing spawn area: 91%
[16:50:25] [Server thread/INFO]: Time elapsed: 5345 ms
[16:50:25] [Server thread/INFO]: Done (5.524s)! For help, type "help"
[16:50:30] [Server thread/INFO]: Stopping the server
[16:50:30] [Server thread/INFO]: Stopping server
[16:50:30] [Server thread/INFO]: Saving players
[16:50:30] [Server thread/INFO]: Saving worlds
[16:50:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[16:50:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:50:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[16:50:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:50:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[16:50:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:50:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:50:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:50:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
```

I see that you mentionned autoconfig1u's version in your post. Do you load it manually?
Starting clothconfig 4.9 it is bundled with it and not needed as a separate mod.

Could be nice if you can provide the list of mods you load.

**Comment by MeeniMc** [comment]
Hey, I have retested with only fallingtree and fabric-api. Nothing else.

### Mods/software:
1. MC 1.16.5 SERVER (win64)
2. fabric-api 0.32.5
3. fallingtree-2.11.1 (unified)

### Replication steps:
1. Start the server for the first time, the server will start and create a new config file `config/fallingtree.json5`
2. Stop the server
3. Restart the server, the server will fail to load with the attached log
4. Erase the config/fallingtree.json5 file, the server loads and create a new config file. 
5. back to step 2. 

```python
[02:33:23] [main/INFO]: Loading for game Minecraft 1.16.5
[02:33:23] [main/INFO]: [FabricLoader] Loading 50 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@15, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.5+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.11.19, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fallingtree@2.11.1, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.5+351679a77d, fabric-object-builders-v0@0.7.2+ca58154a7d
[02:33:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Games/Minecraft/test116/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[02:33:26] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fallingtree'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[0e218850-109c-4f5f-a3b2-2bc59443775d.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[0e218850-109c-4f5f-a3b2-2bc59443775d.jar:?]
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[0e218850-109c-4f5f-a3b2-2bc59443775d.jar:?]
	at fr.raksrinana.fallingtree.fabric.config.Configuration.register(Configuration.java:52) ~[FallingTree-1.16.5-2.11.1.jar:?]
	at fr.raksrinana.fallingtree.fabric.FallingTree.onInitialize(FallingTree.java:14) ~[FallingTree-1.16.5-2.11.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
```

**Comment by Rakambda** [comment]
I can reproduce it, thanks. Will look into it.

**Comment by Rakambda** [comment]
Root cause is `Cannot load class me.shedaniel.autoconfig.gui.registry.GuiRegistry in environment type SERVER`.

**Comment by Rakambda** [comment]
Seems to work on my side now. I let you try it to be sure before I release the fix :
https://www.dropbox.com/t/Poh3xuk5YavEO4st

**Comment by MeeniMc** [comment]
Everything works as intended
